spring:
  datasource:
    url: jdbc:h2:file:./data/project
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      #      first time set create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: schema-h2.sql
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


#  Start your Spring Boot application.
#  Open a web browser and go to http://localhost:8080/h2-console.
#  Enter the JDBC URL (jdbc:h2:mem:project), username (sa), and password (password).
